  platform: template
  switches:
    storeroom_automation_motion:
      value_template: "{{ is_state('automation.storeroom_motion', 'on') }}"
      turn_on:
        service: automation.turn_on
        entity_id: automation.storeroom_motion
      turn_off:
        service: automation.turn_off
        entity_id: automation.storeroom_motion
