homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: !secret home_time_zone
  # Customization file
  customize: !include customize.yaml

# Enables the frontend
frontend:
  themes: !include_dir_merge_named themes/

# Enables the recorder
recorder:

influxdb:
  host: influxdb_host
  port: influxdb_port
  database: !secret influxdb_database
  username: !secret influxdb_user
  password: !secret influxdb_password
  max_retries: 3
  default_measurement: state

panel_iframe:
  bureau_router:
    title: Bureau Router
    url: http://!secret gameroom_router_ip
    icon: mdi:router-wireless-settings
  living_router:
    title: Living Router
    url: http://!secret livingroom_router_ip
    icon: mdi:router-wireless-settings
  motioneye:
    title: MotionEye
    url: !secret motioneye_url
    icon: mdi:eye
  tasmoadmin:
    title: TasmoAdmin
    url: !secret tasmoadmin_url
  grafana:
    title: Grafana
    url: !secret grafana_url
    icon: mdi:chart-multiline
  influxdb:
    title: InfluxDB
    url: !secret influxdb_url
    icon: mdi:chart-line-variant

# Enables configuration UI
config:

http:
  trusted_networks:
    - 192.168.1.0/24
  base_url: !secret http_base_url

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

lovelace:
  mode: yaml

notify:
  - name: homemail
    platform: smtp
    server: smtp.gmail.com
    port: 587
    timeout: 15
    sender: !secret mail_sender
    encryption: starttls
    username:  !secret mail_main
    password: !secret google_app_key
    recipient:
    - !secret mail_main
    - !secret mail_secundary
    - !secret mail_1
    - !secret mail_2
    sender_name: My Home Assistant
  - name: pushbullet
    platform: pushbullet
    api_key: !secret pushbullet_apikey

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

history_graph:
  livingroom:
    name: Livingroom Climate
    entities:
      - sensor.humidity_158d0002379148
      - sensor.temperature_158d0002379148
      - sensor.illumination_158d0001de7134
    hours_to_show: 240
    refresh: 300
  gameroom:
    name: Gameroom Climate
    entities:
      - sensor.temperature_158d000236744c
      - sensor.humidity_158d000236744c
      - sensor.illumination_158d0001f9cdfe
    hours_to_show: 240
    refresh: 300
  veranda:
    name: Veranda Climate
    entities:
      - sensor.humidity_158d00020f4dd3
      - sensor.temperature_158d00020f4dd3
    hours_to_show: 240
    refresh: 300
  internet:
    name: Internet Graph
    entities:
    - sensor.speedtest_ping
    - sensor.speedtest_download
    - sensor.speedtest_upload
    hours_to_show: 240
    refresh: 300

# View all events in a logbook
logbook:

logger:
  default: error
  logs:
    homeassistant.components.device_tracker: error
    homeassistant.components.xiaomi_aqara: error
    homeassistant.components.sensor: error
    homeassistant.components.switch: error
    homeassistant.components.automation: error
    homeassistant.components.scripts: error
    homeassistant.components.group: error
    homeassistant.components.remote: error
    homeassistant.components.light: error
    homeassistant.components.media_player: error

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Text to speech
tts:
  - platform: google

# Cloud
cloud:

group: !include_dir_merge_named groups/
automation: !include_dir_merge_list automations/
script: !include_dir_merge_named scripts/
sensor: !include_dir_list sensors/
light: !include_dir_list lights/
remote: !include remotes.yaml
switch: !include_dir_list switches/
input_select: !include_dir_merge_named input_selects/
input_boolean: !include booleans.yaml
#camera: !include cameras.yaml
scene: !include_dir_merge_list scenes/
#variable: !include variables.yaml

# Mqtt
mqtt:
  broker : !secret mqtt_broker_ip
  client_id: mqttbroker

# Devices
media_player:
  - platform: kodi
    host: !secret livingroom_kodi_ip
    name: kodiliving
  - platform: kodi
    host: !secret gameroom_kodi_ip
    name: kodibureau

# Xiaomi
xiaomi_aqara:
  discovery_retry: 10
  gateways:
    - key: !secret gameroom_gateway_key
      mac: !secret gameroom_gateway_mac
#      host: !secret gameroom_gateway_host
    - key: !secret livingroom_gateway_key
      mac: !secret livingroom_gateway_mac
#      host: !secret livingroom_gateway_host
    - key: !secret stairway_gateway_key
      mac: !secret stairway_gateway_mac
#      host: !secret stairway_gateway_host

ffmpeg:

ifttt:
  key: !secret ifttt_key

device_tracker:
#  - platform: luci
#    host: !secret livingroom_router_ip
#    username: root
#    password: !secret livingroom_router_password
#    track_new_devices: false
  - platform: luci
    host: !secret gameroom_router_ip
    username: root
    password: !secret gameroom_router_password
    track_new_devices: true

sabnzbd:
  api_key: !secret sabnzbd_api_key
  host: !secret sabnzbd_host
  port: !secret sabnzbd_port
  name: Sabnzbd Downloader
