homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: !secret home_time_zone
  # Customization file
  customize: !include customize.yaml
  auth_providers:
    - type: trusted_networks
      trusted_networks:
        - 192.168.1.0/24
        - 10.8.0.0/24

# Enables the frontend
frontend:
  themes: !include_dir_merge_named themes/

system_health:

weather:
  - platform: darksky
    api_key: !secret darksky_api_key
    mode: daily

custom_updater:
  card_urls:
    - https://raw.githubusercontent.com/kalkih/mini-graph-card/master/tracker.json
    - https://raw.githubusercontent.com/kalkih/mini-media-player/master/tracker.json

# Enables the recorder
recorder:
  purge_keep_days: 5

influxdb:
  host: !secret influxdb_host
  default_measurement: state

panel_iframe:
  tasmoadmin:
    title: TasmoAdmin
    url: !secret tasmoadmin_url
    icon: mdi:basket

# Enables configuration UI
config:

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:

lovelace:
  mode: yaml

notify:
  - name: homemail
    platform: smtp
    server: smtp.gmail.com
    port: 587
    timeout: 15
    sender: !secret mail_sender
    encryption: starttls
    username:  !secret mail_main
    password: !secret google_app_key
    recipient:
    - !secret mail_main
    - !secret mail_secundary
    - !secret mail_1
    - !secret mail_2
    sender_name: My Home Assistant
  - name: pushbullet
    platform: pushbullet
    api_key: !secret pushbullet_apikey

# Discover some devices automatically
discovery:

speedtestdotnet:
  scan_interval:
    hours: 4
  monitored_conditions:
    - ping
    - download
    - upload

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

history_graph:
  livingroom:
    name: Livingroom Climate
    entities:
      - sensor.humidity_158d0002379148
      - sensor.livingroom_temperature_sensor
      - sensor.livingroom_lightlevel
    hours_to_show: 240
    refresh: 300
  gameroom:
    name: Gameroom Climate
    entities:
      - sensor.gameroom_temperature
      - sensor.gameroom_humidity
      - sensor.illumination_158d0001f9cdfe
    hours_to_show: 240
    refresh: 300
  veranda:
    name: Veranda Climate
    entities:
      - sensor.veranda_humidity_sensor
      - sensor.veranda_temperature_sensor
    hours_to_show: 240
    refresh: 300
  internet:
    name: Internet Graph
    entities:
    - sensor.speedtest_ping
    - sensor.speedtest_download
    - sensor.speedtest_upload
    hours_to_show: 240
    refresh: 300

# View all events in a logbook
logbook:

logger:
  default: error
  logs:
    homeassistant.components: error
    pydeconz: debug
    homeassistant.components.deconz: debug

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

google:
  client_id: !secret google_client_id
  client_secret: !secret google_secret

# Text to speech
tts:
  - platform: google_translate
    service_name: google_say

# Cloud
cloud:

group: !include_dir_merge_named groups/
automation: !include_dir_merge_list automations/
script: !include_dir_merge_named scripts/
sensor: !include_dir_list sensors/
light: !include_dir_list lights/
remote: !include remotes.yaml
switch: !include_dir_list switches/
input_select: !include_dir_merge_named input_selects/
input_boolean: !include booleans.yaml
#camera: !include cameras.yaml
scene: !include_dir_merge_list scenes/
#variable: !include variables.yaml

# Mqtt
mqtt:
  broker : !secret mqtt_broker_ip
  client_id: mqttbroker

# Devices
media_player:
  - platform: kodi
    host: !secret livingroom_kodi_ip
    name: kodiliving
  - platform: kodi
    host: !secret gameroom_kodi_ip
    name: kodibureau

# Xiaomi
xiaomi_aqara:
  discovery_retry: 10
  gateways:
    - key: !secret gameroom_gateway_key
      mac: !secret gameroom_gateway_mac
#      host: !secret gameroom_gateway_host
    - key: !secret livingroom_gateway_key
      mac: !secret livingroom_gateway_mac
#      host: !secret livingroom_gateway_host
    - key: !secret stairway_gateway_key
      mac: !secret stairway_gateway_mac
#      host: !secret stairway_gateway_host

ffmpeg:

ifttt:
  key: !secret ifttt_key

device_tracker:

sabnzbd:
  api_key: !secret sabnzbd_api_key
  host: !secret sabnzbd_host
  port: !secret sabnzbd_port
  name: Sabnzbd Downloader

emulated_hue:
  listen_port: 8125
  expose_by_default: false
  entities:
    script.livingroom_rgb_colorchanger_off:
      name: Livingroom RGB Off
      hidden: false
    script.livingroom_rgb_colorchanger:
      name: Livingroom RGB Color Changer
      hidden: false
    switch.livingroom_sofa_plug:
      name: Livingroom Sofa Plug
      hidden: false
    switch.livingroom_dressoir_plug:
      name: Livingroom Dressoir Plug
      hidden: false
    script.gameroom_rgb_colorchanger_off:
      name: Gameroom RGB Off
      hidden: false
    script.gameroom_rgb_colorchanger:
      name: Gameroom RGB Color Changer
      hidden: false
    switch.gameroom_sonoff_desklight:
      name: Gameroom Desk Light
      hidden: false
