- alias: Livingroom Audiocast stopped
  trigger:
    - platform: state
      entity_id: media_player.living_room_audio
      to: 'off'
  condition:
    - condition: template
      value_template: "{{ is_state_attr('remote.livingroom_hub', 'current_activity', 'Music') }}"
  action:
    service: scene.turn_on
    entity_id: scene.livingroom_hub_off
- alias: Livingroom Audiocast playing
  trigger:
    - platform: state
      entity_id: media_player.living_room_audio
      to: 'playing'
    - platform: state
      entity_id: media_player.living_room_audio
      to: 'paused'
  condition:
    - condition: template
      value_template: "{{ is_state_attr('remote.livingroom_hub', 'current_activity', 'PowerOff') }}"
  action:
    service: scene.turn_on
    entity_id: scene.livingroom_audiocast

- alias: Livingroom Chromecast stopped
  trigger:
    platform: state
    entity_id: media_player.living_room_video
    to: 'off'
  condition:
    - condition: template
      value_template: "{{ is_state_attr('remote.livingroom_hub', 'current_activity', 'Chromecast') }}"
  action:
    service: scene.turn_on
    entity_id: scene.livingroom_hub_off
- alias: Livingroom Chromecast playing
  trigger:
    - platform: state
      entity_id: media_player.living_room_video
      to: 'playing'
    - platform: state
      entity_id: media_player.living_room_video
      to: 'paused'
  condition:
    - condition: template
      value_template: "{{ is_state_attr('remote.livingroom_hub', 'current_activity', 'PowerOff') }}"
  action:
    service: scene.turn_on
    entity_id: scene.livingroom_chromecast

- alias: Livingroom Audiocast Still Playing
  trigger:
    - platform: template
      value_template: "{% if is_state( 'media_player.living_room_audio', 'off')%}false{% else %}true{% endif %}"
  condition:
    - condition: template
      value_template: "{{ state_attr('remote.livingroom_hub', 'current_activity') | string != 'Music' }}"
  action:
    - service: media_player.media_stop
      entity_id: media_player.living_room_audio
    - service: media_player.turn_off
      entity_id: media_player.living_room_audio

- alias: Livingroom Kodi Input Selected
  trigger:
    - platform: state
      entity_id: media_player.kodiliving
      to: 'playing'
  action:
    service: switch.turn_on
    entity_id: switch.livingroom_kodi
