  - alias: SSL expiry notification
    initial_state: 'on'
    trigger:
      platform: numeric_state
      entity_id: sensor.ssl_cert_expiry
      below: 10
    action:
      service: script.notify_all
      data:
        title: "SSL certificate expiration warning"
        message: 'Warning - SSL certificate expires in 10 days and has not been automatically renewed'
  - alias: 'Alarm Notifications'
    trigger:
      platform: state
      entity_id: group.alarm_notification_sensors
      to: 'on'
    condition:
      - condition: state
        entity_id: input_boolean.alarm_armed
        state: 'on'
    action:
      service: script.notify_all
      data_template:
        title: "Er is beweging in het huis."
        message: >
          Er is beweging gedetecteerd in het huis. De volgende sensors hebben beweging gezien :
          {% if is_state(binary_sensor.livingroom_motion_sensor, 'on') %} - Living sensor{% endif %}
          {% if is_state(binary_sensor.veranda_motion_sensor, 'on') %} - Veranda sensor{% endif %}
          {% if is_state(binary_sensor.gameroom_motion, 'on') %} - Mancave sensor{% endif %}
          {% if is_state(binary_sensor.landing_motion_sensor, 'on') %} - Gang boven sensor{% endif %}
  - alias: Alarm Siren
    initial_state: 'on'
    trigger:
      platform: state
      entity_id: group.alarm_siren_sensors
      to: 'on'
    condition:
      - condition: state
        entity_id: input_boolean.alarm_armed
        state: 'on'
    action:
      - service: script.notify_all
        data:
          title: "Het alarm is aan het afgaan."
          message: "Er is thuis beweging gedetecteerd en het alarm is aangezet!"
      - service: script.alarm_siren_on
        data:
          ringtone_id: 8
          ringtone_vol: 90
  - alias: Alarm Off
    initial_state: 'on'
    trigger:
      platform: state
      entity_id: input_boolean.alarm_armed
      to: 'off'
    action:
      - service: script.notify_all
        data:
          title: "Het alarm is afgegaan en wordt nu uitgezet."
          message: "Het alarm is nu afgezet!"
      - service: script.alarm_siren_off
