- alias: 'SSL expiry notification'
  trigger:
    platform: numeric_state
    entity_id: sensor.ssl_cert_expiry
    below: 10
  action:
    service: script.notify_all
    data:
      title: "SSL certificate expiration warning"
      message: 'Warning - SSL certificate expires in 10 days and has not been automatically renewed'