- alias: Stairway NightLight Motion
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_158d000276e199
    to: 'on'
  condition:
  - condition: numeric_state
    entity_id: sensor.illumination_7811dcded4dc
    below: '30'
  - condition: or
    conditions:
    - condition: sun
      after: sunset
    - condition: sun
      before: sunrise
  action:
  - service: light.turn_on
    entity_id: light.gateway_light_7811dcb9c795
    data:
      entity_id: light.gateway_light_7811dcb9c795
      rgb_color: [0, 0, 255]
- alias: Stairway No Motion
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_158d000276e199
    to: 'off'
    for:
      minutes: '3'
  action:
  - service: light.turn_off
    entity_id: light.gateway_light_7811dcb9c795
